# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guifinal.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import serial
from time import sleep
import cv2, imutils
from threading import Thread
import numpy as np
from pyfirmata import ArduinoMega, SERVO

# board = ArduinoMega('/dev/cu.usbmodem101')
# pin = 10
# board.digital[pin].mode = SERVO

global ser
# ser = serial.Serial('/dev/cu.usbmodem101', baudrate=9600, timeout=1,
#                     parity=serial.PARITY_NONE,
#                     stopbits=serial.STOPBITS_ONE,
#                     bytesize=serial.EIGHTBITS
#                     )

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1470, 920)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(70, 20, 831, 461))
        self.graphicsView.setObjectName("graphicsView")
        self.startbutton = QtWidgets.QPushButton(self.centralwidget)
        self.startbutton.setGeometry(QtCore.QRect(130, 500, 151, 51))
        self.startbutton.setObjectName("startbutton")
        self.stopbutton = QtWidgets.QPushButton(self.centralwidget)
        self.stopbutton.setGeometry(QtCore.QRect(380, 500, 171, 51))
        self.stopbutton.setObjectName("stopbutton")
        self.gripperslider = QtWidgets.QSlider(self.centralwidget)
        self.gripperslider.setGeometry(QtCore.QRect(1070, 110, 281, 91))
        self.gripperslider.setOrientation(QtCore.Qt.Horizontal)
        self.gripperslider.setObjectName("gripperslider")
        self.gripperslider.setMinimum(100)
        self.gripperslider.setMaximum(145)
        self.gripperslider.setValue(110)
        self.gripperslider.valueChanged.connect(self.gripperslidercontrol)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1160, 190, 101, 31))
        self.label.setObjectName("label")
        self.brightslider = QtWidgets.QSlider(self.centralwidget)
        self.brightslider.setGeometry(QtCore.QRect(20, 100, 22, 261))
        self.brightslider.setOrientation(QtCore.Qt.Vertical)
        self.brightslider.setObjectName("brightslider")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 380, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1050, 170, 25, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1350, 160, 31, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 740, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(650, 740, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(760, 740, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(850, 740, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(710, 800, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(710, 670, 60, 16))
        self.label_11.setObjectName("label_11")
        self.surgeslider = QtWidgets.QSlider(self.centralwidget)
        self.surgeslider.setGeometry(QtCore.QRect(1080, 300, 22, 160))
        self.surgeslider.setOrientation(QtCore.Qt.Vertical)
        self.surgeslider.setObjectName("surgeslider")
        self.surgeslider.setMinimum(1300)
        self.surgeslider.setMaximum(1700)
        self.surgeslider.setValue(1500)
        self.surgeslider.valueChanged.connect(self.surgeslidercontrol)
        self.yawslider = QtWidgets.QSlider(self.centralwidget)
        self.yawslider.setGeometry(QtCore.QRect(1230, 290, 22, 160))
        self.yawslider.setOrientation(QtCore.Qt.Vertical)
        self.yawslider.setObjectName("yawslider")
        self.yawslider.setMinimum(1300)
        self.yawslider.setMaximum(1700)
        self.yawslider.setValue(1500)
        self.yawslider.valueChanged.connect(self.yawslidercontrol)
        self.swayslider = QtWidgets.QSlider(self.centralwidget)
        self.swayslider.setGeometry(QtCore.QRect(1360, 290, 22, 160))
        self.swayslider.setOrientation(QtCore.Qt.Vertical)
        self.swayslider.setObjectName("swayslider")
        self.swayslider.setMinimum(1300)
        self.swayslider.setMaximum(1700)
        self.swayslider.setValue(1500)
        self.swayslider.valueChanged.connect(self.swayslidercontrol)
        self.killswitch = QtWidgets.QPushButton(self.centralwidget)
        self.killswitch.setGeometry(QtCore.QRect(660, 500, 151, 51))
        self.killswitch.setObjectName("killswitch")
        self.killswitch.clicked.connect(self.killswitchcontrol)
        self.rthruster = QtWidgets.QSpinBox(self.centralwidget)
        self.rthruster.setGeometry(QtCore.QRect(710, 640, 48, 24))
        self.rthruster.setObjectName("rthruster")
        self.rthruster.valueChanged.connect(self.rthrustercontrol)
        self.fthruster1 = QtWidgets.QSpinBox(self.centralwidget)
        self.fthruster1.setGeometry(QtCore.QRect(560, 700, 48, 24))
        self.fthruster1.setObjectName("fthruster1")
        self.fthruster1.valueChanged.connect(self.fthruster1control)
        self.dthruster1 = QtWidgets.QSpinBox(self.centralwidget)
        self.dthruster1.setGeometry(QtCore.QRect(650, 700, 48, 24))
        self.dthruster1.setObjectName("dthruster1")
        self.dthruster1.valueChanged.connect(self.dthruster1control)
        self.dthruster2 = QtWidgets.QSpinBox(self.centralwidget)
        self.dthruster2.setGeometry(QtCore.QRect(760, 700, 48, 24))
        self.dthruster2.setObjectName("dthruster2")
        self.dthruster2.valueChanged.connect(self.dthruster2control)
        self.fthruster2= QtWidgets.QSpinBox(self.centralwidget)
        self.fthruster2.setGeometry(QtCore.QRect(860, 700, 48, 24))
        self.fthruster2.setObjectName("fthruster2")
        self.fthruster2.valueChanged.connect(self.fthruster2control)
        self.lthruster = QtWidgets.QSpinBox(self.centralwidget)
        self.lthruster.setGeometry(QtCore.QRect(710, 770, 48, 24))
        self.lthruster.setObjectName("lthruster")
        self.lthruster.valueChanged.connect(self.lthrustercontrol)
        self.gripperspinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.gripperspinbox.setGeometry(QtCore.QRect(1170, 80, 48, 24))
        self.gripperspinbox.setObjectName("gripperspinbox")
        self.gripperspinbox.setMinimum(90)
        self.gripperspinbox.setMaximum(135)
        self.gripperspinbox.setValue(100)
        self.gripperspinbox.setSingleStep(5)
        self.gripperspinbox.valueChanged.connect(self.gripperspinboxcontrol)
        self.surgespinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.surgespinbox.setGeometry(QtCore.QRect(1070, 500, 48, 24))
        self.surgespinbox.setObjectName("surgespinbox")
        self.surgespinbox.setMinimum(1300)
        self.surgespinbox.setMaximum(1700)
        self.surgespinbox.setValue(1500)
        self.surgespinbox.setSingleStep(10)
        self.surgespinbox.valueChanged.connect(self.surgespinboxcontrol)
        self.yawspinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.yawspinbox.setGeometry(QtCore.QRect(1220, 500, 48, 24))
        self.yawspinbox.setObjectName("yawspinbox")
        self.yawspinbox.setMinimum(1300)
        self.yawspinbox.setMaximum(1700)
        self.yawspinbox.setValue(1500)
        self.yawspinbox.setSingleStep(10)
        self.yawspinbox.valueChanged.connect(self.yawspinboxcontrol)
        self.swayspinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.swayspinbox.setGeometry(QtCore.QRect(1350, 500, 48, 24))
        self.swayspinbox.setObjectName("swayspinbox")
        self.swayspinbox.setMinimum(1300)
        self.swayspinbox.setMaximum(1700)
        self.swayspinbox.setValue(1500)
        self.swayspinbox.setSingleStep(10)
        self.swayspinbox.valueChanged.connect(self.swayspinboxcontrol)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1070, 560, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1220, 560, 60, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1350, 560, 60, 16))
        self.label_13.setObjectName("label_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1470, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def gripperslidercontrol(self):
        endAngle = self.gripperslider.value()
        # for angle in range(0, endAngle):
        #     board.digital[pin].write(angle)

    def gripperspinboxcontrol(self):
        endAngle = self.gripperspinbox.value()
        # for angle in range(0, endAngle):
        #     board.digital[pin].write(angle)
    
    def surgeslidercontrol(self):
        self.dthruster1.setValue(1500)
        self.dthruster2.setValue(1500)
        self.fthruster1.setValue(1500)
        self.fthruster2.setValue(1500)
        val = self.surgeslider.value()
        self.rthruster.setValue(val)
        self.lthruster.setValue(val)
        ser.write(str(self.fthruster1.value()) + str(self.fthruster2.value()) + str(self.lthruster.value()) + str(self.rthruster.value()) + str(self.dthruster1.value()) + str(self.dthruster2.value()) + str(self.gripperslider.value()) + '/')


    def surgespinboxcontrol(self):
        self.dthruster1.setValue(1500)
        self.dthruster2.setValue(1500)
        self.lthruster.setValue(1500)
        self.rthruster.setValue(1500)
        val = self.surgespinbox.value()
        self.fthruster1.setValue(val)
        self.fthruster2.setValue(val)
        ser.write(str(self.fthruster1.value()) + str(self.fthruster2.value()) + str(self.lthruster.value()) + str(self.rthruster.value()) + str(self.dthruster1.value()) + str(self.dthruster2.value()) + str(self.gripperslider.value()) + '/')

    def yawslidercontrol(self):
        self.dthruster1.setValue(1500)
        self.dthruster2.setValue(1500)
        self.fthruster1.setValue(1500)
        self.fthruster2.setValue(1500)
        val = self.yawslider.value()
        self.rthruster.setValue(val)
        negvalue = val-1500
        self.lthruster.setValue(1500-negvalue)
        ser.write(str(self.fthruster1.value()) + str(self.fthruster2.value()) + str(self.lthruster.value()) + str(self.rthruster.value()) + str(self.dthruster1.value()) + str(self.dthruster2.value()) + str(self.gripperslider.value()) + '/')

    def yawspinboxcontrol(self):
        self.dthruster1.setValue(1500)
        self.dthruster2.setValue(1500)
        self.fthruster1.setValue(1500)
        self.fthruster2.setValue(1500)
        val = self.yawspinbox.value()
        self.rthruster.setValue(val)
        negvalue = val-1500
        self.lthruster.setValue(1500-negvalue)
        ser.write(str(self.fthruster1.value()) + str(self.fthruster2.value()) + str(self.lthruster.value()) + str(self.rthruster.value()) + str(self.dthruster1.value()) + str(self.dthruster2.value()) + str(self.gripperslider.value()) + '/')

    def swayslidercontrol(self):
        self.dthruster1.setValue(1500)
        self.dthruster2.setValue(1500)
        self.fthruster1.setValue(1500)
        self.fthruster2.setValue(1500)
        val = self.swayslider.value()
        self.rthruster.setValue(val)
        self.lthruster.setValue(val)
        ser.write(str(self.fthruster1.value()) + str(self.fthruster2.value()) + str(self.lthruster.value()) + str(self.rthruster.value()) + str(self.dthruster1.value()) + str(self.dthruster2.value()) + str(self.gripperslider.value()) + '/')

    def swayspinboxcontrol(self):
        self.dthruster1.setValue(1500)
        self.dthruster2.setValue(1500)
        self.fthruster1.setValue(1500)
        self.fthruster2.setValue(1500)
        val = self.swayspinbox.value()
        self.rthruster.setValue(val)
        self.lthruster.setValue(val)
        ser.write(str(self.fthruster1.value()) + str(self.fthruster2.value()) + str(self.lthruster.value()) + str(self.rthruster.value()) + str(self.dthruster1.value()) + str(self.dthruster2.value()) + str(self.gripperslider.value()) + '/')

    def killswitchcontrol(self):
        pass

    def rthrustercontrol(self):
        pass

    def fthruster1control(self):
        pass

    def dthruster1control(self):
        pass

    def dthruster2control(self):
        pass

    def fthruster2control(self):
        pass

    def lthrustercontrol(self):
        pass

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startbutton.setText(_translate("MainWindow", "Start"))
        self.stopbutton.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "      Gripper"))
        self.label_2.setText(_translate("MainWindow", "Bright"))
        self.label_4.setText(_translate("MainWindow", "90"))
        self.label_5.setText(_translate("MainWindow", "135"))
        self.label_6.setText(_translate("MainWindow", "Forward"))
        self.label_7.setText(_translate("MainWindow", "BottomF"))
        self.label_8.setText(_translate("MainWindow", "BottomB"))
        self.label_9.setText(_translate("MainWindow", "Backward"))
        self.label_10.setText(_translate("MainWindow", "Left"))
        self.label_11.setText(_translate("MainWindow", "Right"))
        self.killswitch.setText(_translate("MainWindow", "Kill Switch"))
        self.label_3.setText(_translate("MainWindow", "Surge"))
        self.label_12.setText(_translate("MainWindow", "    Yaw"))
        self.label_13.setText(_translate("MainWindow", "Sway"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
